export const FETCH_CITIES = 'FETCH_CITIES';
export const UPDATE_CITIES = 'UPDATE_CITIES';

export const FETCH_COUNTRIES = 'FETCH_COUNTRIES';
export const UPDATE_COUNTRIES = 'UPDATE_COUNTRIES';

export const FETCH_DATEOFBIRTH = 'FETCH_DATEOFBIRTH';
export const UPDATE_DATEOFBIRTH = 'UPDATE_DATEOFBIRTH';

export const FETCH_DATEOFDEATH = 'FETCH_DATEOFDEATH';
export const UPDATE_DATEOFDEATH = 'UPDATE_DATEOFDEATH';

export const FETCH_STATES = 'FETCH_STATES';
export const UPDATE_STATES = 'UPDATE_STATES';
